version: '2'
services:
  app:
    build: .
    depends_on:
      - selenium
    volumes:
      - .:/project
    environment:
      - POETRY_PYPI_TOKEN_PYPI=${POETRY_PYPI_TOKEN_PYPI}
      - PYTHONPATH=./src
    command:
      >
        bash -i -c -e
        "
        poetry install --no-root;
        tail -f /dev/null;
        "

  selenium:
    image: selenium/standalone-chrome
    environment:
      - VNC_NO_PASSWORD=1 # Don't ask for a password
      - SE_NODE_SESSION_TIMEOUT=1000
    ports:
      - ${SELENIUM_PORT:-4444}:4444
      - ${SELENIUM_VNC_PORT:-5900}:5900
